apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ecommerce-cluster
  region: us-east-1

nodeGroups:
  - name: large-workers
    instanceType: t3.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    volumeSize: 20
    ssh:
      allow: false
    labels:
      role: large-worker
