apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-platform
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/doyindevops/ecommerce-platform.git
    targetRevision: main
    path: k8s
  syncPolicy:
    automated: {}  # <- You can remove this if you want manual sync
