apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: adedoyine/cart-service:v2  # Change if needed
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: default
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
