config:
  service: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Tag kube.*
        multiline.parser docker, cri
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

  outputs: |
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            elasticsearch-master.logging.svc.cluster.local
        Port            9200
        HTTP_User       elastic
        HTTP_Passwd     sNHbnAHXZmYUuoOC
        TLS             On
        TLS.Verify      Off
        Logstash_Format On
        Logstash_Prefix kube
        Suppress_Type_Name On
        Generate_ID     On
        Retry_Limit     False
        Replace_Dots    On

    [OUTPUT]
        Name            es
        Match           host.*
        Host            elasticsearch-master.logging.svc.cluster.local
        Port            9200
        HTTP_User       elastic
        HTTP_Passwd     sNHbnAHXZmYUuoOC
        TLS             On
        TLS.Verify      Off
        Logstash_Format On
        Logstash_Prefix node
        Suppress_Type_Name On
        Generate_ID     On
        Retry_Limit     False
        Replace_Dots    On

    [OUTPUT]
    name            es
    match           *
    host            elasticsearch-master
    port            9200
    tls             On
    tls.verify      Off
    http_user       elastic
    http_passwd     sNHbnAHXZmYUuoOC
    index           fluentbit-index
    logstash_format On
    replace_dots    On
    generate_id     On


    

        

